#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Nov 06 10:36:22 +07 2018
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_axis_adc_v1_0_behav -key {Behavioral:sim_1:Functional:tb_axis_adc_v1_0} -tclbatch tb_axis_adc_v1_0.tcl -view /home/kdich/workspace/zynq/vivado/7020/ip_repo/axis_adc_v1_0_project/axis_adc_v1_0_project.sim/tb_axis_adc_v1_0_behav.wcfg -log simulate.log
