# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/write_bitstream.xdc

# XDC: new/pinout.xdc

# Block Designs: bd/zsys/zsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys || ORIG_REF_NAME==zsys} -quiet] -quiet

# IP: bd/zsys/ip/zsys_processing_system7_0_0/zsys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_processing_system7_0_0 || ORIG_REF_NAME==zsys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_dmac_0_0/zsys_axi_dmac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_dmac_0_0 || ORIG_REF_NAME==zsys_axi_dmac_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axis_adc_0_0/zsys_axis_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axis_adc_0_0 || ORIG_REF_NAME==zsys_axis_adc_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_smc_0/zsys_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_smc_0 || ORIG_REF_NAME==zsys_axi_smc_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_rst_ps7_0_100M_0/zsys_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_rst_ps7_0_100M_0 || ORIG_REF_NAME==zsys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_ps7_0_axi_periph_0/zsys_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_ps7_0_axi_periph_0 || ORIG_REF_NAME==zsys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xlconcat_0_0/zsys_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xlconcat_0_0 || ORIG_REF_NAME==zsys_xlconcat_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_gpio_0_0/zsys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_gpio_0_0 || ORIG_REF_NAME==zsys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_axi_quad_spi_0_0/zsys_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_axi_quad_spi_0_0 || ORIG_REF_NAME==zsys_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_xbar_0/zsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_xbar_0 || ORIG_REF_NAME==zsys_xbar_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_system_ila_0_0/zsys_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_system_ila_0_0 || ORIG_REF_NAME==zsys_system_ila_0_0} -quiet] -quiet

# IP: bd/zsys/ip/zsys_auto_pc_0/zsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zsys_auto_pc_0 || ORIG_REF_NAME==zsys_auto_pc_0} -quiet] -quiet

# XDC: bd/zsys/zsys_ooc.xdc
