# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/zsys_system_ila_0_0.xci
# IP: The module: 'zsys_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/bd_f448.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f448 || ORIG_REF_NAME==bd_f448} -quiet] -quiet

# IP: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/bd_f448_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f448_ila_lib_0 || ORIG_REF_NAME==bd_f448_ila_lib_0} -quiet] -quiet

# IP: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_1/bd_f448_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f448_g_inst_0 || ORIG_REF_NAME==bd_f448_g_inst_0} -quiet] -quiet

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f448_ila_lib_0 || ORIG_REF_NAME==bd_f448_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f448_ila_lib_0 || ORIG_REF_NAME==bd_f448_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/bd_f448_ila_lib_0_ooc.xdc

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/bd_f448_ooc.xdc

# IP: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/zsys_system_ila_0_0.xci
# IP: The module: 'zsys_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/bd_f448.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f448 || ORIG_REF_NAME==bd_f448} -quiet] -quiet

# IP: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/bd_f448_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f448_ila_lib_0 || ORIG_REF_NAME==bd_f448_ila_lib_0} -quiet] -quiet

# IP: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_1/bd_f448_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f448_g_inst_0 || ORIG_REF_NAME==bd_f448_g_inst_0} -quiet] -quiet

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f448_ila_lib_0 || ORIG_REF_NAME==bd_f448_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f448_ila_lib_0 || ORIG_REF_NAME==bd_f448_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/ip/ip_0/bd_f448_ila_lib_0_ooc.xdc

# XDC: /home/kdich/workspace/zynq/vivado/7010/adc_eth/adc_eth.srcs/sources_1/bd/zsys/ip/zsys_system_ila_0_0/bd_0/bd_f448_ooc.xdc
